CREATE DATABASE IF NOT EXISTS `stuck-mg-test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'doupi_test'@'127.0.0.1' IDENTIFIED BY 'DoupiTest2026!#';
GRANT ALL PRIVILEGES ON `stuck-mg-test`.* TO 'doupi_test'@'127.0.0.1';
FLUSH PRIVILEGES;
