/**
 * @fileoverview 展示文案数据字典（本地静态来源）
 * 说明：运行时文案仅使用本地 DISPLAY_TEXT，不再接收远端覆盖。
 *
 * 命名约定（新增文案时请优先复用既有 key）：
 * - BTN_*: 按钮文案，例如 `BTN_SAVE`
 * - LABEL_*: 字段标签，例如 `LABEL_PHONE`
 * - TITLE_*: 卡片/弹窗/区块标题，例如 `TITLE_SETTINGS`
 * - PLACEHOLDER_*: 输入占位，例如 `PLACEHOLDER_ENTER_NAME`
 * - MODAL_*: 弹窗标题/正文，例如 `MODAL_CONFIRM_LOGOUT_TITLE`
* - STATUS_* / STAT_*: 状态值，例如 `STATUS_ENABLED`
 * - TIP_/HINT_/DESC_: 说明、提示与描述性文案
 *
 * 维护流程：
 * 1) 先 `rg` 搜索是否已有语义等价 key；
 * 2) 若无，再按上面前缀新增；
 * 3) 页面仅通过 `displayDict.text(KEY)` 引用；
 * 4) 不要在页面内保留同语义硬编码中文。
 * 5) 接口错误文案见 `errorDict.js`；表单校验见 `validationDict.js`。
 */

const DISPLAY_TEXT = Object.freeze({
  // Core Defaults
  CAMPUS_DEFAULT: "华襄小学",
  NO_APPOINTMENT_NO: "暂无预约号",
  NO_AVAILABLE_TIME_SLOTS: "暂无可用时段",
  NO_BOOKING_NOTICE: "暂无预约须知内容",
  NO_BOOKINGS: "暂无预约记录",
  NO_CAMPUS_INFO: "暂无校园信息",
  NO_CAMPUS_INTRO: "暂无简介",
  NO_CHANGES_TO_DISCARD: "暂无可丢弃的更改",
  NO_MATCHED_ROLES: "暂无匹配的角色",
  NO_MESSAGES: "暂无消息",
  NO_MORE_REACHED: "已经到底啦",
  NO_MORE_TEXT: "已经到底啦",
  NO_PERMISSION: "无权限访问",
  NO_PERMISSION_ACCESS: "无权限访问",
  NO_PHONE_BOUND: "未绑定手机号",
  NO_PHONE_CONTACT: "暂无联系电话",
  NO_PHONE_LEFT: "未留手机号",
  NO_PRIVACY_POLICY: "暂无隐私政策内容",
  NO_QR_DOWNLOAD: "暂无二维码可下载",
  NO_RECENT_BOOKINGS: "最近7天暂无待核销或已核销预约",
  NO_RECORD: "暂无记录",
  NO_TIME_SLOTS: "暂无时间段，请新增",
  NO_UNCHECKED_BOOKINGS: "暂无待核销的预约",
  NO_USER_AGREEMENT: "暂无用户协议内容",
  NO_USERS: "暂无用户",
  NONE: "无",
  PENDING: "待定",
  UNASSIGNED: "未分配",
  UNBOUND: "未绑定",
  UNFILLED: "未填写",
  UNKNOWN: "未知",
  UNSET: "未设置",
  USER_DEFAULT: "用户",

  // Actions Buttons
  BTN_ACKNOWLEDGED: "我知道了",
  BTN_ADD: "新增",
  BTN_ADD_BANNER: "添加轮播图",
  BTN_ADD_IMAGE: "添加图片",
  BTN_ADD_VIDEO: "添加视频",
  BTN_BACK_LIST: "返回列表",
  BTN_BATCH_USER_MANAGE: "批量用户管理",
  BTN_BOOK_NOW: "立即预约",
  BTN_CANCEL: "取消",
  BTN_CANCEL_BOOKING: "取消预约",
  BTN_CANCEL_NOW: "确认取消",
  BTN_CLEAR: "清除",
  BTN_CLOSE: "关闭",
  BTN_CONFIRM: "确认",
  BTN_CONFIRM_BIND_DIRECTOR: "确认绑定到该主任",
  BTN_CONFIRM_CANCEL: "确认取消",
  BTN_CONFIRM_DELETE: "确认删除",
  BTN_CONFIRM_LOGOUT: "确认退出",
  BTN_COPY: "复制",
  BTN_CREATE_ROLE: "创建角色",
  BTN_DELETE: "删除",
  BTN_DELETE_VIDEO: "删除视频",
  BTN_DETAIL: "详情",
  BTN_DISABLE: "禁用",
  BTN_DISABLE_ALL: "全部关闭",
  BTN_DISCARD_CHANGES: "丢弃更改",
  BTN_DOWNLOAD_QR: "下载二维码",
  BTN_EDIT_ROLE: "编辑角色",
  BTN_ENABLE: "启用",
  BTN_ENABLE_ALL: "全部开启",
  BTN_EXPORT_FILTERED_RESULT: "导出当前筛选结果",
  BTN_EXPORT_STATS_REPORT: "导出统计报表",
  BTN_GENERATE_BIND_QR: "生成绑定二维码",
  BTN_GO_SETTING: "去设置",
  BTN_GOT_IT: "我知道了",
  BTN_LOGOUT: "退出登录",
  BTN_MARK_ALL_READ: "全部已读",
  BTN_PREVIEW: "预览",
  BTN_READ_AND_AGREE: "我已阅读并同意",
  BTN_REGENERATE: "重新生成",
  BTN_REGENERATE_QR: "重新生成二维码",
  BTN_RESET: "重置",
  BTN_RESET_ALL: "重置全部",
  BTN_RESTORE_DEFAULT: "恢复默认",
  BTN_RETHINK: "再想想",
  BTN_RETURN: "返回",
  BTN_SAVE: "保存",
  BTN_SAVE_CONFIG: "保存配置",
  BTN_SAVE_DICT: "保存字典",
  BTN_SAVE_IMAGE: "保存图片",
  BTN_SAVE_INFO: "保存信息",
  BTN_SAVE_NEW: "保存新增",
  BTN_SAVE_PERMISSION_CONFIG: "保存权限配置",
  BTN_SCAN_BIND_DIRECTOR: "扫一扫绑定主任",
  BTN_SCAN_BIND_DIRECTOR_SHORT: "扫一扫绑定主任",
  BTN_SHARE_QR: "分享二维码",
  BTN_SHOW_VERIFY_QR: "显示核销码",
  BTN_THINK_AGAIN: "再想想",
  BTN_UNBIND: "解除绑定",
  BTN_UNBOUND: "已解绑",
  BTN_USE_WECHAT_AVATAR_NAME: "使用微信头像昵称",
  BTN_VIEW_DETAIL: "查看详情",

  // Labels Titles Placeholders
  LABEL_ADVANCE_BOOKING_DAYS: "提前预约天数",
  LABEL_APPOINTMENT_NO: "预约号",
  LABEL_ASSIGN_PERMISSIONS: "分配权限",
  LABEL_AVATAR: "头像",
  LABEL_BINDING_SUCCESS: "绑定成功",
  LABEL_BOOKING_COUNT: "预约次数",
  LABEL_BOOKING_TIME: "预约时间",
  LABEL_CAMPUS_NAME: "校园名称",
  LABEL_CANCEL_BOOKING_HOURS: "取消预约时限（小时）",
  LABEL_CONTACT_PHONE: "联系电话",
  LABEL_CURRENT_SCHOOL: "就读学校",
  LABEL_CURRENT_STATUS: "当前状态",
  LABEL_CURRENT_VALUE: "当前值",
  LABEL_DAILY_BOOKING_LIMIT: "每日预约上限",
  LABEL_DEFAULT_VALUE: "默认值",
  LABEL_DETAIL_ADDRESS: "详细地址",
  LABEL_DUPLICATED: "重复",
  LABEL_EARLIER: "更早",
  LABEL_END_TIME: "结束时间",
  LABEL_ERROR: "错误",
  LABEL_ID_CARD_NO: "身份证号",
  LABEL_INVALID: "无效",
  LABEL_LAST_LOGIN: "最近登录",
  LABEL_LINKED_USERS: "关联用户",
  LABEL_MINIPROGRAM_NAME: "小程序名称",
  LABEL_MOTTO: "个性签名",
  LABEL_NAME: "姓名",
  LABEL_NOTICE: "通知",
  LABEL_PARENT: "家长",
  LABEL_PARENT_NAME: "家长姓名",
  LABEL_PERMISSION_CONFIG: "权限配置",
  LABEL_PHONE: "手机号",
  LABEL_PHONE_NUMBER: "手机号",
  LABEL_QR_VALID_DURING_PERIOD: "有效期内可使用",
  LABEL_QR_VALID_UNTIL_PREFIX: "有效期至 ",
  LABEL_REGISTER_TIME: "注册时间",
  LABEL_RESPONSIBLE_TEACHER: "预约老师",
  LABEL_ROLE: "角色",
  LABEL_ROLE_CODE: "角色编码",
  LABEL_ROLE_NAME: "角色名称",
  LABEL_ROLE_PREFIX: "角色：",
  LABEL_SCHOOL_NATURE: "办学性质",
  LABEL_SCHOOL_SECTION: "学段",
  LABEL_SEND_TIME_PREFIX: "发送时间：",
  LABEL_SESSION_ID: "会话ID",
  LABEL_START_TIME: "开始时间",
  LABEL_STATUS: "状态",
  LABEL_STUDENT_NAME: "学生姓名",
  LABEL_SUBMIT_TIME: "提交时间",
  LABEL_SUCCESS: "成功",
  LABEL_SYSTEM_NOTICE: "系统通知",
  LABEL_TODAY: "今天",
  LABEL_VALID: "有效",
  LABEL_VISIT_DATE: "参观日期",
  LABEL_VISIT_TIME: "参观时间",
  LABEL_VISIT_TIME_SLOT: "参观时段",
  LABEL_WARNING: "警告",
  PLACEHOLDER_BOOKING_NOTICE_RICH: "请输入预约须知（支持富文本）",
  PLACEHOLDER_ENDING_MESSAGE: "探校结束后展示给家长的寄语内容（选填）",
  PLACEHOLDER_ENTER_NAME: "请输入姓名",
  PLACEHOLDER_ENTER_ROLE_DESC: "请输入角色描述信息",
  PLACEHOLDER_ENTER_ROLE_NAME: "请输入角色名称",
  PLACEHOLDER_MOTTO: "写一句个性签名吧~",
  PLACEHOLDER_PHONE_EXAMPLES: "示例：\n13800000000，13900000000\n或 13800000000、13900000000\n或 13800000000,13900000000",
  PLACEHOLDER_PRIVACY_POLICY_RICH: "请输入隐私政策（支持富文本）",
  PLACEHOLDER_ROLE_CODE_FORMAT: "仅支持英文、数字、下划线",
  PLACEHOLDER_ROLE_DESC_SCOPE: "简要描述该角色的职责和权限范围",
  PLACEHOLDER_ROLE_NAME_EXAMPLE: "如：区域经理、客服人员等",
  PLACEHOLDER_SCHOOL_INTRO: "请输入学校简介，介绍学校历史、办学特色、师资力量等",
  PLACEHOLDER_SEARCH_BOOKING: "搜索预约号、姓名、手机号",
  PLACEHOLDER_SEARCH_ROLE: "搜索角色名称或编码",
  PLACEHOLDER_SELECT: "请选择",
  PLACEHOLDER_SELECT_SCHOOL_NATURE: "请选择办学性质",
  PLACEHOLDER_SELECT_SCHOOL_SECTION: "请选择学段",
  PLACEHOLDER_USER_AGREEMENT_RICH: "请输入用户协议（支持富文本）",
  TAB_BASIC_PARAMS: "基础参数",
  TAB_BOOKING_NOTICE: "预约须知",
  TAB_PRIVACY_POLICY: "隐私政策",
  TAB_USER_AGREEMENT: "用户协议",
  TITLE_ABOUT_US: "关于我们",
  TITLE_ACCOUNT_SETTINGS: "账号设置",
  TITLE_ADD_TIME_SLOT: "新增时间段",
  TITLE_APPOINTMENT_DETAIL: "预约详情",
  TITLE_APPOINTMENT_INFO: "预约信息",
  TITLE_APPOINTMENT_PROGRESS: "预约进度",
  TITLE_BANNER_GALLERY: "Banner展示图",
  TITLE_BANNER_MANAGE: "轮播图管理",
  TITLE_BASIC_INFO: "基础信息",
  TITLE_BIND_CONFIRM: "招生绑定确认",
  TITLE_BOOKABLE_TIME_SLOTS: "可预约时间段",
  TITLE_BOOKING_RULES: "预约规则",
  TITLE_CLASSROOM_GALLERY: "功能教室图集",
  TITLE_CREATE_ROLE: "新建角色",
  TITLE_DELETE_USER: "删除用户",
  TITLE_EDIT_ROLE: "编辑角色",
  TITLE_ENDING_MESSAGE: "结束寄语",
  TITLE_ENVIRONMENT_GALLERY: "环境图集",
  TITLE_INAPP_NOTIFY: "站内消息通知",
  TITLE_MESSAGE_NOTICE: "消息通知",
  TITLE_MESSAGE_NOTIFICATION: "消息通知",
  TITLE_NOTIFICATION_SETTINGS: "通知设置",
  TITLE_PARENT_INFO: "家长信息",
  TITLE_PERMISSION_COUNT: "权限数量",
  TITLE_PHONE_MULTI_INPUT: "手机号（可多行 / 多种分隔符）",
  TITLE_PREVIEW: "预览",
  TITLE_PRIVACY_POLICY: "隐私政策",
  TITLE_PRIVACY_SECURITY: "隐私与安全",
  TITLE_PROFILE: "个人资料",
  TITLE_ROLE_DESC: "角色描述",
  TITLE_ROLE_SELECT: "角色选择",
  TITLE_SCHOOL_INTRO: "学校简介",
  TITLE_SCHOOL_INTRO_VIDEO: "学校简介视频",
  TITLE_SETTINGS: "设置",
  TITLE_SMS_NOTIFY: "短信通知",
  TITLE_STADIUM_GALLERY: "体育场馆图集",
  TITLE_STUDENT_INFO: "学生信息",
  TITLE_USER_AGREEMENT: "用户协议",
  TITLE_USER_DETAIL: "用户详情",
  TITLE_USER_STATS: "用户统计",
  TITLE_VERIFY_QRCODE: "核销二维码",
  TITLE_WARM_TIPS: "温馨提示",

  // Modals Tips Descriptions
  BADGE_BUILTIN: "内置",
  BADGE_HOME_DISPLAY: "首页展示",
  DESC_BIND_CONFIRM: "扫描主任二维码后，点击下方按钮完成绑定",
  DESC_APPOINTMENT_PENDING_TIPS: "1. 请按预约时段提前10分钟到校。\n2. 请向工作人员出示核销二维码并配合登记。\n3. 如无法到访，请在预约开始前及时取消并重新选择时间。",
  DESC_SHOW_QRCODE_TO_STAFF: "请向工作人员出示此二维码",
  HINT_BUILTIN_ROLE_CODE_READONLY: "系统内置角色编码不可修改",
  HINT_PERMISSION_CONFIG_AT_PAGE: "详细权限配置请在「权限管理」页面操作",
  HINT_PHONE_SPLIT_SUPPORTED: "支持逗号、顿号、分号、空格、换行等分隔符；会自动去重与校验。",
  HINT_ROLE_CODE_READONLY_AFTER_CREATE: "用于系统内部标识，创建后不可修改",
  MODAL_CANCEL_APPOINTMENT_CONTENT: "取消后将无法恢复，请确认是否继续？",
  MODAL_CANCEL_APPOINTMENT_TITLE: "确认取消预约",
  MODAL_CANCEL_BOOKING_CONTENT: "取消后将无法恢复，确定要取消此预约吗？",
  MODAL_CANCEL_BOOKING_TITLE: "确认取消预约",
  MODAL_CANNOT_DELETE_TITLE: "无法删除",
  MODAL_CONFIRM_ACTION_TITLE: "确认操作",
  MODAL_CONFIRM_CANCEL_BOOKING_CONTENT: "确定要取消该预约吗？此操作不可恢复。",
  MODAL_CONFIRM_CANCEL_TITLE: "确认取消",
  MODAL_CONFIRM_DELETE_TITLE: "确认删除",
  MODAL_CONFIRM_LOGOUT_CONTENT: "退出后需要重新登录才能使用",
  MODAL_CONFIRM_LOGOUT_TITLE: "确认退出登录",
  MODAL_DELETE_IMAGE_CONTENT: "确定要删除这张图片吗？",
  MODAL_DELETE_ROLE_TITLE: "删除角色",
  MODAL_DELETE_VIDEO_CONTENT: "确定要删除该视频吗？",
  MODAL_DISCARD_CONFIRM_TITLE: "确认丢弃",
  MODAL_EXPORT_BOOKINGS_TITLE: "导出预约数据",
  MODAL_EXPORT_TITLE: "导出报表",
  MODAL_PERMISSION_REQUIRED_CONTENT: "请允许访问您的相册以保存二维码图片",
  MODAL_PERMISSION_REQUIRED_TITLE: "需要相册权限",
  MODAL_PROMPT_TITLE: "提示",
  MODAL_RESET_CAMPUS_CONTENT: "确定放弃当前编辑并恢复最新已保存内容吗？",
  MODAL_RESET_CONFIRM_TITLE: "确认重置",
  MODAL_RESET_QR_CONTENT: "重置后当前二维码将立即失效，是否继续？",
  MODAL_RESET_QR_TITLE: "确认重置",
  MODAL_SCAN_INVITE_CONTENT: "是否跳转到预约页面？",
  MODAL_SCAN_INVITE_TITLE: "检测到预约邀请码",
  MODAL_UNBIND_CONTENT_SUFFIX: "」的绑定关系吗？解除后该老师将无法使用系统功能。",
  MODAL_UNBIND_TITLE: "确认解除绑定",
  TIP_FIRST_LOGIN_COMPLETE_PROFILE: "首次登录请先完善头像、昵称和个性签名",
  TIP_PROFILE_PHONE_VERIFY: "修改手机号后需要重新验证，请确保新手机号可以正常接收短信",

  // Status and States
  LOCKED_LABEL: "锁定",
  OPTIONAL: "选填",
  OVERVIEW_CUSTOM: "自定义",
  OVERVIEW_ENABLED: "已启用",
  OVERVIEW_ROLE_TOTAL: "角色总数",
  REQUIRED: "必填",
  STAT_ALL: "全部",
  STATUS_BINDING: "绑定中...",
  STATUS_BOUND: "已绑定",
  STATUS_CANNOT_CANCEL: "当前状态不可取消",
  STATUS_DISABLED: "已禁用",
  STATUS_DISABLED_SHORT: "已停用",
  STATUS_ENABLED: "已启用",
  UNIT_PERSON: "人",

  // Booking Appointment
  APPOINTMENT_LABEL_CONTACT_PHONE: "联系电话",
  APPOINTMENT_LABEL_VISIT_DATE: "参观日期",
  APPOINTMENT_LABEL_VISIT_TIME: "参观时间",
  APPOINTMENT_LABEL_VISITOR_COUNT: "参观人数",
  APPOINTMENT_LABEL_VISITOR_NAME: "访客姓名",
  APPOINTMENT_STAT_CANCELLED: "已取消",
  APPOINTMENT_STAT_PENDING: "待核销",
  APPOINTMENT_STAT_VERIFIED: "已核销",
  APPOINTMENT_SUBTITLE_CANCELLED: "预约已取消",
  LABEL_CANCEL_REASON: "取消原因",
  CANCEL_REASON_NONE: "暂无说明",
  APPOINTMENT_SUBTITLE_COMPLETED: "预约流程已结束",
  APPOINTMENT_SUBTITLE_PENDING: "请按时到校参加活动",
  APPOINTMENT_SUBTITLE_VERIFIED: "已完成核销，感谢您的参与",
  BOOKING_CANCELLED: "已取消预约",
  BOOKING_DETAIL_APPOINTMENT_INFO: "预约信息",
  BOOKING_DETAIL_APPOINTMENT_TIME: "预约时间",
  BOOKING_DETAIL_CONTACT_PHONE: "联系电话",
  BOOKING_DETAIL_COPY_HINT: "点击复制",
  BOOKING_DETAIL_CREATE_TIME: "提交时间",
  BOOKING_DETAIL_CURRENT_SCHOOL: "目前就读",
  BOOKING_DETAIL_ID_CARD: "身份证号",
  BOOKING_DETAIL_NO: "预约编号",
  BOOKING_DETAIL_PARENT_INFO: "家长信息",
  BOOKING_DETAIL_PARENT_NAME: "家长姓名",
  BOOKING_DETAIL_RECEIVE_TEACHER: "接待老师",
  BOOKING_DETAIL_RELATED_TEACHER: "预约老师",
  BOOKING_DETAIL_REMARK: "备注信息",
  BOOKING_DETAIL_STATUS: "当前状态",
  BOOKING_DETAIL_STUDENT_INFO: "学生信息",
  BOOKING_DETAIL_STUDENT_NAME: "学生姓名",
  BOOKING_DETAIL_TIME_RECORD: "时间记录",
  BOOKING_DETAIL_UPDATE_TIME: "更新时间",
  BOOKING_NOTICE_READ_DONE: "已阅读预约须知",
  CANCEL_SUCCESS: "取消成功",
  CANCELLING: "取消中...",
  CLICK_GENERATE_QR: "点击生成二维码",
  EXPORT_SUCCESS: "导出成功",
  FILTERED_RECENT_PREFIX: "已筛选最近",
  FILTERED_RECENT_SUFFIX: "天",
  GENERATE_SUCCESS: "生成成功",
  GENERATING: "生成中...",
  GENERATING_QR: "生成中...",
  LOAD_MORE_PULL_UP: "上拉加载更多",
  LOAD_MORE_TEXT: "上拉加载更多",
  PROCESSED_COUNT_PREFIX: "已处理 ",
  PROCESSED_COUNT_SUFFIX: " 条",
  PROCESSING: "处理中...",
  RESETTING: "重置中...",
  RESULT_BOOKING_COUNT_SUFFIX: " 条预约记录",
  RESULT_TEACHER_COUNT_SUFFIX: " 位老师",
  RESULT_TOTAL_PREFIX: "共 ",
  SAVING: "保存中...",
  UPLOADING: "上传中...",
  VERIFY_SUCCESS: "核销成功",

  // Auth Role Permission
  ALL_DISABLED_DONE: "已全部关闭",
  ALL_ENABLED_DONE: "已全部开启",
  DELETE_SUCCESS: "删除成功",
  DICT_ADMIN_ONLY_TIP: "仅管理员可修改。修改后页面实时按字典值渲染。",
  DISABLED_DONE: "已禁用",
  ENABLED_DONE: "已启用",
  GET_PHONE_IN_PROGRESS: "获取手机号中...",
  LOGIN_CANCEL_PHONE_AUTH: "你已取消手机号授权",
  SMS_LOGIN_CODE_DISABLED: "后台未开启验证码功能，请改用手机号快捷登录或联系管理员",
  LOGIN_IN_PROGRESS: "登录中...",
  LOGIN_REQUIRE_WECHAT_PHONE: "请授权获取微信绑定手机号",
  LOGIN_SUCCESS: "登录成功",
  PERMISSION_CORE_LOCKED: "该权限为系统核心权限，不可关闭",
  PERMISSION_COUNT_SUFFIX: "项权限",
  PERMISSION_HELP_CONTENT: "锁定的权限为该角色的核心必要权限，不可关闭。其他权限可根据实际需求灵活配置。修改权限后，对应角色的用户将在下次登录时生效。",
  PERMISSION_HELP_DISABLED_DOT: "灰色圆点表示该权限已关闭",
  PERMISSION_HELP_ENABLED_DOT: "绿色圆点表示该权限已开启",
  PERMISSION_HELP_LOCKED: "标记为锁定的权限为核心必要权限，不可关闭",
  PERMISSION_HELP_TITLE: "权限说明",
  PERMISSION_LIST_HINT: "锁定项为核心权限不可修改",
  PERMISSION_LIST_TITLE: "功能权限列表",
  PERMISSION_MENU_REFRESHED: "权限已更新，菜单已刷新",
  PERMISSION_SAVED: "权限配置已保存",
  PERMISSION_UPDATED_MENU_REFRESHED: "权限已更新，菜单已刷新",
  ROLE_ADMIN: "超级管理员",
  ROLE_MANAGER: "管理员",
  ROLE_CREATED_SUCCESS: "角色创建成功",
  ROLE_DIRECTOR: "招生主任",
  ROLE_PARENT: "家长",
  ROLE_TEACHER: "招生老师",
  ROLE_UPDATE_SUCCESS: "角色修改成功",
  SAVE_SUCCESS: "保存成功",
  SEARCH_KEY_OR_TEXT: "搜索 key 或文案",
  UPDATE_SUCCESS: "更新成功",
  WECHAT_PROFILE_FILLED: "已填充微信资料",
  WECHAT_PROFILE_NOT_FOUND: "未获取到微信资料",

  // Campus School
  BANNER_HINT: "上传后将直接展示在首页轮播图，最多 5 张，建议尺寸 750x360。",
  BANNER_MAX_FIVE: "轮播图最多5张",
  UPLOAD_HINT_MAX_FIVE: "最多5张",
  UPLOAD_HINT_MAX_NINE: "最多9张",
  UPLOAD_HINT_VIDEO_OPTIONAL: "选填，时长不超过60秒",

  // Messaging Notifications
  EMPTY_NO_NOTIFICATION_DESC: "您还没有收到任何通知消息",
  MARK_ALL_READ_SUCCESS: "全部标记为已读",
  NOTIFICATION_DISABLED: "已关闭消息通知",
  NOTIFICATION_ENABLED: "已开启消息通知",

  // Miscellaneous
  ADD_SUCCESS: "添加成功",
  ALBUM_SAVE_SUCCESS: "已保存到相册",
  BIND_REQUIRED_BEFORE_QR: "请先绑定招生主任后再生成二维码",
  COPY_SUCCESS: "已复制到剪贴板",
  CREATING: "创建中...",
  DISCARD_ALL_TAB_DONE: "已丢弃所有Tab更改",
  DISCARD_CURRENT_TAB_DONE: "已丢弃当前Tab更改",
  EMPTY_MATCHED_TEACHERS: "暂无匹配的老师记录",
  EMPTY_NO_BOOKINGS_DESC: "您还没有任何预约记录",
  EMPTY_NO_BOOKINGS_IN_STATUS_PREFIX: "该状态下",
  EMPTY_NO_MATCHED_DICT: "无匹配字典项",
  EMPTY_TRY_ADJUST_SEARCH_FILTER: "试试调整搜索或筛选条件",
  FEATURE_IN_DEVELOPMENT: "功能开发中",
  FILTER_EMPTY_BOOKINGS: "当前筛选条件下暂无预约记录",
  FILTER_EMPTY_LOGS: "当前筛选条件下暂无日志数据",
  FILTER_EMPTY_USERS: "当前筛选条件下暂无用户数据",
  LINK_COPIED: "链接已复制",
  LOADING_TEXT: "加载中...",
  LOGOUT_IN_PROGRESS: "正在退出...",
  LOGOUT_SUCCESS: "已退出登录",
  RESET_SUCCESS_OLD_INVALID: "重置成功，旧码已失效",
  SCAN_PREPARING: "准备扫码...",
  SCOPE_EMPTY_BOOKINGS: "当前权限范围内暂无预约记录",
  SCOPE_EMPTY_LOGS: "当前权限范围内暂无日志数据",
  SCOPE_EMPTY_USERS: "当前权限范围内暂无用户数据",
  SWITCH_ALLOW_SAME_DAY_CANCEL: "允许当天取消",
  SWITCH_ENABLE_INAPP_NOTIFY: "启用站内消息提醒",
  SWITCH_SMS_LOGIN_CODE: "启用验证码短信",
  SWITCH_SMS_APPOINTMENT_REMINDER: "启用预约提醒短信",
  SWITCH_REMINDER_BEFORE_2HOUR: "预约前两小时提醒",
  SWITCH_REMINDER_BEFORE_DAY: "预约前一天下午提醒",
  SWITCH_REQUIRE_ID_CARD: "要求身份证",
  SWITCH_REQUIRE_PHONE: "要求手机号",
  SYSTEM_ROLE_CANNOT_DELETE: "系统内置角色不可删除",
  SYSTEM_ROLE_CANNOT_DISABLE: "系统内置角色不可禁用",
  TOOLBAR_BOLD: "加粗",
  TOOLBAR_ITALIC: "斜体",
  TOOLBAR_LIST: "列表",
  TOOLBAR_UNDERLINE: "下划线",
  TOTAL_BOOKING_COUNT_SUFFIX: " 条记录",
  UNBIND_DONE: "已解除绑定",
  UPLOAD_SUCCESS: "上传成功",
  USER_DELETE_SUCCESS: "删除成功"
});

function hydrateFromStorage() {
  // 仅保留兼容调用，始终返回本地字典快照
  return DISPLAY_TEXT;
}

function text(key) {
  return DISPLAY_TEXT[key] || "";
}

function valueOr(value, key) {
  if (value === null || value === undefined) return text(key);
  if (typeof value === "string" && value.trim() === "") return text(key);
  return value;
}

function setOverrides(overrides) {
  // 已切换为本地字典模式，忽略远端覆盖
  return overrides;
}

function clearOverrides() {
  // 已切换为本地字典模式，保留空实现兼容旧调用
  return;
}

module.exports = {
  DISPLAY_TEXT,
  hydrateFromStorage,
  text,
  valueOr,
  setOverrides,
  clearOverrides
};
